### ISSUE TITLE
Is Sorting possible? Will other Add operations wait?

### ISSUE THREAD

**Issue by MPasadu** [i3arnon/ConcurrentHashSet#10]
Hey,
thank you for your implementation. it works great so far.
I have a question regarding sorting or any kind of manipulation.

If I do a big calculation like sorting or any other operation that takes some time. And I don't want any changes interfering in the mean time. Is it enough to just acquire all locks, do the operation (like sorting) and then release the locks?

e.g.

```
var concurrentHashSet = [initialization here];
concurrentHashSet.AcquireAllLocks();
var sortedArray = concurrentHashSet.OrderBy([Some ordering here]).toArray();
var concurrentHashSet = new ConcurrentHashSet(sortedArray);
concurrentHashSet.ReleaseAllLocks();
```

**Comment by i3arnon** [comment]
Well, I guess yes, that's enough. But what specifically are you trying to accomplish?
`AcquireAllLocks` and `ReleaseAllLocks` are currently private methods.
Also, in your code you replace the instance in `concurrentHashSet` so you're locking one instance and releasing another.

I probably should add a `ToArray` method like `ConcurrentDictionary` has that allows to get a snapshot out.

**Comment by MPasadu** [comment]
Yes, correct releasing the lock from the new instance doesn't make sense. I was just wondering what would happen if while sorting another thread would try to add a new item. Would it get lost?

I am currently writing a testcase to find out.

EDIT: I actually had the wrong approach. I can just return your ConcurrentHashSet as a List and then sort the list. If new items are added in that time, it doesn't matter for my use case. Thank you for your time!
