### ISSUE TITLE
Compatibility with Xamarin

### ISSUE THREAD

**Issue by Almeonamy** [i3arnon/ConcurrentHashSet#11]
Is this package compatible with Xamarin?
I tried add it to my project but get error: "Can not resolve reference: `ConcurrentCollections`, referenced by `XXX`. Please add a NuGet package or assembly reference for `ConcurrentCollections`, or remove the reference to `XXX`"

**Comment by i3arnon** [comment]
Well, it's compatible with .NET Standard and Xamarin implements the standard so in theory it should work.
But unfortunately I haven't actually tested it.

Does the assembly actually reach the output folder?
