### ISSUE TITLE
Null items

### ISSUE THREAD

**Issue by daveaglick** [i3arnon/ConcurrentHashSet#3]
The framework `HashSet<T>` accepts null items and can check for null items. I.e., the following works fine:

```
HashSet<string> hs = new HashSet<string>();
hs.Add("test");
hs.Contains("test").Dump();  // true
hs.Contains(null).Dump();  // false
hs.Add(null);
hs.Contains(null).Dump();  // true
```

The `ConcurrentHashSet<T>` throws for null values on `Add()`, `Contains()`, and `TryRemove()`. Wondering if behavior should match `HashSet<T>` and allow null values (that would be my preference)?

**Comment by i3arnon** [comment]
I must say I'm surprised.
I guess I always assumed `HashSet` can't accept `null`s because it can't hash them.
But evidently that's not the case.
I agree matching `HashSet` is the way to go...
