### ISSUE TITLE
Brainstorming: ConcurrentObservableDictionary, ConcurrentObservableHashSet

### ISSUE THREAD

**Issue by nopara73** [i3arnon/ConcurrentHashSet#5]
First of all: great work!  
  
Ever wondered creating ConcurrentObservableDictionary? My implementation is just "fine". I'd love to use a great one.  
Also a ConcurrentObservableHashSet could be a nice complementary stuff too.

**Comment by jnm2** [comment]
My instinct is that the observable part is best handled in a domain-specific wrapper around the dictionary rather than a general purpose observable dictionary.

**Comment by nopara73** [comment]
Right. Thanks for the answer.

**Comment by jnm2** [comment]
Disclaimer: I am not @i3arnon :smile:

**Comment by nopara73** [comment]
Ops

**Comment by i3arnon** [comment]
@nopara73, by Observable do you mean in the WPF sense?
It didn't cross my mind. The last time I used WPF was about 7 years ago.

**Comment by nopara73** [comment]
Never used WPF, so I cannot confirm that, but I think observability is pretty self explanatory.
For reference here's how I hacked together an ConcurrentObservableHashSet in the limited timeframe I had for that, using the ConcurrentHashSet I found in this repo.
https://github.com/nopara73/HBitcoin/blob/master/src/HBitcoin/Helpers/ConcurrentObservableHashSet.cs

**Comment by jnm2** [comment]
What is ConcurrentObservableHashSet actually getting used for? Once you're locking like that, you may as well use a non-concurrent hash set.

**Comment by nopara73** [comment]
> What is ConcurrentObservableHashSet actually getting used for?

This wasn't an overengineered code written to "make sure nothing goes wrong". But rather the threads were doing stupid things, so I had to make it concurrent which fixed my problems.  
I think the observable part is self-explanatory.

> Once you're locking like that, you may as well use a non-concurrent hash set.

Not really, I don't lock everywhere. In fact if that'd be the case nobody would use this nuget package, but wrap a hashset using 2 locked block :)
